In [3]:
import pandas as pd

In [5]:
y = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep='\t')
print(y.head())

   order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa
1         1         1                                   Izze
2         1         1                       Nantucket Nectar
3         1         1  Chips and Tomatillo-Green Chili Salsa
4         2         2                           Chicken Bowl

                                  choice_description item_price
0                                                NaN     $2.39
1                                       [Clementine]     $3.39
2                                            [Apple]     $3.39
3                                                NaN     $2.39
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

In [8]:
l = pd.DataFrame({'Cars': ['BMW', 'Audi', 'Toyota'], 'Price': [50000, 45000, 30000]})
l

     Cars  Price
0     BMW  50000
1    Audi  45000
2  Toyota  30000

# Indexing

In [10]:
cars = pd.DataFrame({'German':['BMW','Volkswagen','Mercedes-Benz'],'JDM':['Toyota','Subaru','Mitshubishi']}, index=['car01','car02','car03'])

cars

              German          JDM
car01            BMW       Toyota
car02     Volkswagen       Subaru
car03  Mercedes-Benz  Mitshubishi

In [16]:
#Series

indieGames = pd.Series(['Game1','Game56','Game34'])
indieGames

0     Game1
1    Game56
2    Game34
dtype: str

# Pandas Series w Idex

In [18]:
Information123 = pd.Series(['Hollow Knight','Inside','Shovel Knight'],index=[1,2,3])
Information123

1    Hollow Knight
2           Inside
3    Shovel Knight
dtype: str

In [ ]:
#Reading Data 

yd = read.csv('')